version: '3.7'
services:
   main:
      image: opuscapita/sftp-gateway:dev
      command: /bin/sh ./setup-consul.sh && mvn spring-boot:run

   tnt:
      image: opuscapita/tnt:dev
      command: 'npm run dev'